import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import type { Group } from 'three'
import type { HeroSceneControls } from './heroScene.types'

const nodes: readonly [number, number, number][] = [[-1.2, .7, -.3], [-.55, .35, .2], [.1, .72, -.25], [.75, .37, .18], [1.15, -.35, -.2], [.4, -.72, .22], [-.42, -.5, -.15], [-1.05, -.16, .14]]
const links: readonly [number, number][] = [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,0],[1,6],[2,5],[1,3]]
function Linework() { const geometry = useMemo(() => { const positions = new Float32Array(links.length * 6); links.forEach(([start,end], index) => { positions.set(nodes[start], index * 6); positions.set(nodes[end], index * 6 + 3) }); return new THREE.BufferGeometry().setAttribute('position', new THREE.BufferAttribute(positions, 3)) }, []); return <lineSegments geometry={geometry}><lineBasicMaterial color="#edebe5" transparent opacity={.42} /></lineSegments> }
function Rails() { const geometry = useMemo(() => new THREE.BufferGeometry().setAttribute('position', new THREE.BufferAttribute(new Float32Array([-1.5,-.95,-.4,1.5,-.95,-.4,-1.5,.95,-.4,1.5,.95,-.4,-1.35,-1.15,.35,1.35,1.15,.35]), 3)), []); return <lineSegments geometry={geometry}><lineBasicMaterial color="#edebe5" transparent opacity={.15} /></lineSegments> }
export function EngineeringLattice({ pointer, scrollProgress, isVisible }: HeroSceneControls) { const group = useRef<Group>(null); const signal = useRef<THREE.Mesh>(null); useFrame((state, delta) => { if (!group.current || !signal.current || !isVisible) return; const progress = scrollProgress.current; group.current.rotation.y = THREE.MathUtils.damp(group.current.rotation.y, pointer.current.x * .16 + progress * .13, 2.4, delta); group.current.rotation.x = THREE.MathUtils.damp(group.current.rotation.x, pointer.current.y * .09 - progress * .08, 2.4, delta); group.current.position.z = THREE.MathUtils.damp(group.current.position.z, progress * -.34, 2.4, delta); const scale = 1 + progress * .12 + Math.min(.08, Math.max(0, state.clock.elapsedTime - 1.1) * .08); signal.current.scale.setScalar(THREE.MathUtils.damp(signal.current.scale.x, scale, 3, delta)) }); return <group ref={group} scale={.92}><Rails /><Linework />{nodes.map((position,index) => <mesh key={index} position={position}><sphereGeometry args={[index === 2 ? .05 : .032, 8, 8]} /><meshBasicMaterial color={index === 2 ? '#c8d751' : '#edebe5'} transparent opacity={index === 2 ? .95 : .72} /></mesh>)}<mesh ref={signal}><octahedronGeometry args={[.16,0]} /><meshStandardMaterial color="#c8d751" emissive="#c8d751" emissiveIntensity={.6} roughness={.65} /></mesh></group> }
